[package]
name = "cudacracker"
version = "0.1.0"
edition = "2021"

[dependencies]
cc = "1.2.5"
clap = { version = "4.5.37", features = ["derive"] }
env_logger = "0.11.8"
hex = "0.4.3"
itertools = "0.14.0"
log = "0.4.27"

[build-dependencies]
cc = "1.0"
